### PR TITLE
Organ Mods framework

### PR DESCRIPTION
**Pull request by XDTM**
So, here's my pitch for experimental organs: organ mods!

Organ mods determine the extra effects of an experimental organ. They're separated in minor, normal, and major, which will affect their rarity and how many of each can fit in the same organ.

The idea is that creating an experimental organ would roll random mods, depending on how much the machine is upgraded; after that you can treat the organ to remove, add, or reroll mods, for a price.
You can spam organs, hoping to be lucky and get a really good organ on creation; or you can dedicate time and resources to craft the organ as you want it. You can mass produce mediocre organs to give away, or fine-tune them for a few elect <s>test subjects</s> patients.

Negative mods serve as a way to balance the rng of good symptoms, while also serving as devious traitor weapons, causing delayed death or a certain degree of control over the target (mind-controllable brain?)

This PR contains the base procs for this system and a few examples, where you can see there are generic or organ specific mods. I'll work on actual organ generation/crafting if you like the idea.

### CODE REVIEW

**Comment by FuryMcFlurry** [comment]
The Burrowing organ mod seems like a good idea, if not a tad powerful. however if organs have a limited amount of mods this would be fine. as you a sacrificing potential organ mod slots for ease of use.

**Comment by FuryMcFlurry** [comment]
oh hey its still being worked on, Nice.
If you need anything done pm me on discord. Fury#6398

**Comment by FuryMcFlurry** [comment]
rip

**Comment by XDTM** [comment]
Not rip, i've just been working on it on my own branch

**Pull request closed without merging**
